#import "../thesis.typ": c, ca, cp, cy

In labor-management bargaining, lobbying contests, and litigation, the two sides compete not only over resources but also over timing: when to act is itself a strategic variable. When one party understands its own stake far better than its opponent, the incentives to move early or late cease to be symmetric. The first mover can commit ex ante, but its transparent action thereby exposes its private information; the second mover retains flexibility but correspondingly forfeits the initiative. #c("fu2006") studies a two-player Tullock contest in which the informed player ($I$) privately observes his prize value while the uninformed player ($U$) knows only its prior distribution, and shows that $I$ typically prefers to move second. The intuition is that moving first reveals the level of $I$'s valuation to $U$ and erodes the strategic value of private information, whereas moving second allows $I$ to react optimally after observing $U$'s effort while preserving his informational advantage.

This conclusion, however, rests on a specific belief mechanism. $U$'s best response is sensitive to $I$'s type, so $I$'s effort transmits type information; the resulting signaling channel sustains a pooling equilibrium and makes waiting a strict preference for $I$. We modify this framework by assuming that $I$'s type affects only $I$'s own prize value and does not enter $U$'s continuation best response. Under this assumption, $U$'s posterior belief about $I$'s type cannot influence $U$'s strategy, so the signaling mechanism breaks down. The timing decision is no longer a signaling game; it reduces to a pure comparison of ex ante expected payoffs.

The existing contest literature approaches our question from two directions: the effect of asymmetric information on equilibrium effort, and the endogenous determination of the order of moves. #c("hurley1998") analyze the impact of private valuations on the Cournot-Nash equilibrium and find that asymmetric information shifts equilibrium effort away from the full-information benchmark. #c("warneryd2003") further shows that informational advantage carries strategic value in itself: in equilibrium, the informed player exerts higher effort than under full information. These studies treat the order of moves as exogenously given. The analysis of endogenous timing in contests originates with the seminal duopoly study of #c("hamilton1990"); #c("hoffmann2012") extend this framework to general rent-seeking models and show that first- and second-mover advantages depend on the strategic complementarity of efforts. #c("baikleelee2022") characterize equilibrium timing in three-player Tullock contests. These papers assume that valuations are common knowledge. More recently, #c("protopappas2025") introduces asymmetric information into a Tullock contest with endogenous timing and shows that cost uncertainty can, under certain conditions, reverse the standard "weak-leader" conclusion. In that setting, however, the asymmetric information lies in future effort costs and the timing decision itself carries a signaling role — the informed player's choice of timing transmits cost information to the uninformed. This paper focuses instead on private information about prize values and closes the signaling channel at the effort level, so that the analysis returns to a structural comparison of ex ante expected payoffs.

We build on #c("fu2006") by retaining the basic framework of ex ante timing choice and generalizing $I$'s private valuation to an arbitrary distribution. As concrete examples, we work with the two-point distribution and the uniform distribution. The two-point distribution separates the roles of the mean prize value $mu$ and the dispersion $delta$, which helps isolate the sources of timing incentives. The uniform distribution exhibits a continuous-type threshold structure, revealing how $mu$, $delta$, and the public prize value $V$ jointly determine the timing preference.

Our main results are threefold. First, the $I U$ subgame admits a unique separating equilibrium. Because $U$'s best response does not depend on the posterior belief, no pooling equilibrium can be sustained, and this conclusion is distribution-free. Second, the timing decision should be evaluated through ex ante expected payoffs — that is, by comparing $I$'s ex ante expected utility in the $I U$ and $S S$ subgames. Type-level gains from waiting are merely an ex post decomposition of this difference and are not, by themselves, sufficient to determine the timing preference. Third, $V$, $mu$, and $delta$ jointly determine the timing preference; comparing $mu$ to $V$ alone is insufficient to predict whether $I$ prefers to move first.

Our contribution is to clarify the foundation on which separation rests in contests with asymmetric information. Relative to #c("fu2006"), we change the economic location of the private information so that the existence of a separating equilibrium becomes a consequence of the contest structure itself rather than a particular belief assumption or equilibrium refinement. To our knowledge, this distribution-free form of the separation result has not been explicitly discussed in the existing literature.

The remainder of the paper proceeds as follows. Section 2 reviews the relevant literature; Section 3 sets up the model; Section 4 solves the equilibria of the $S S$, $U I$, and $I U$ subgames; Section 5 analyzes timing incentives and welfare; Section 6 develops the extension with partially correlated types; Section 7 concludes.
