project:
  type: default
  render:
    - summary.qmd

lang: zh-TW

format:
  pdf:
    documentclass: article
    classoption: 12pt
    papersize: a4
    pdf-engine: xelatex
    include-in-header:
      - preamble.tex
    toc: false
    number-sections: false
    output-file: summary.pdf
