project:
  type: default
  render:
    - main.qmd

bibliography: refs.bib
lang: en
reference-section-title: "References"

crossref:
  def-title: Definition
  lem-title: Lemma
  thm-title: Theorem
  prp-title: Proposition
  cor-title: Corollary

format:
  pdf:
    documentclass: article
    classoption: 12pt
    papersize: a4
    pdf-engine: xelatex
    cite-method: natbib
    biblio-style: plainnat
    include-in-header:
      - preamble.tex
    keep-tex: true
    toc: true
    number-sections: true
    output-file: main.pdf
