project:
  type: default
  render:
    - en/main.qmd
    - zh/main.qmd

bibliography: refs.bib

format:
  pdf:
    documentclass: article
    classoption: 12pt
    papersize: a4
    pdf-engine: xelatex
    cite-method: natbib
    biblio-style: plainnat
    keep-tex: false
    toc: true
    number-sections: true
